package jp.boatai.app

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.time.LocalDate
import java.time.ZoneId

data class ModelARecentVirtualLoadResult(
    val records: List<PredictionRecord>,
    val throughDate: String?,
    val windowStart: String?,
    val generatedAt: String?,
    val error: String? = null,
    val fromCache: Boolean = false,
    val summary: ModelARecentVirtualSummary? = null
)

data class ModelARecentPointBreakdown(
    val points: Int, val races: Int, val hits: Int, val hitRate: Double,
    val stake: Int, val payout: Int, val profit: Int, val roi: Double,
    val averageStake: Double, val averageWinningPayout: Double
)

data class ModelARecentVirtualSummary(
    val races: Int, val hits: Int, val stake: Int, val payout: Int, val profit: Int,
    val roi: Double, val averagePoints: Double, val averageStake: Double,
    val pointBreakdown: List<ModelARecentPointBreakdown>
)

/**
 * Loads the rolling retrospective Model A feed generated by GitHub Actions.
 *
 * These records are intentionally kept separate from PredictionHistoryStore:
 * they are forecast-quality / virtual-settlement records generated after the fact,
 * and must never influence the live purchase recommendation or performance profile.
 */
class ModelARecentVirtualRepository(context: Context) {
    private val prefs = context.applicationContext
        .getSharedPreferences("boat_ai_model_a_recent_virtual_v1", Context.MODE_PRIVATE)

    suspend fun load(): ModelARecentVirtualLoadResult = withContext(Dispatchers.IO) {
        val remote = runCatching {
            val text = httpGet("$REMOTE_URL?ts=${System.currentTimeMillis()}")
            parse(text).also {
                prefs.edit().putString(KEY_CACHE, text).apply()
            }
        }
        remote.getOrNull()?.let { return@withContext it }

        val cached = prefs.getString(KEY_CACHE, null)
        if (!cached.isNullOrBlank()) {
            runCatching { parse(cached) }.getOrNull()?.let {
                return@withContext it.copy(
                    error = "最新の過去AI仮想成績を取得できないため端末キャッシュを表示しています",
                    fromCache = true
                )
            }
        }

        ModelARecentVirtualLoadResult(
            records = emptyList(),
            throughDate = null,
            windowStart = null,
            generatedAt = null,
            error = remote.exceptionOrNull()?.message ?: "過去AI仮想成績を取得できませんでした"
        )
    }

    internal fun parse(text: String): ModelARecentVirtualLoadResult {
        val root = JSONObject(text)
        require(root.optInt("schemaVersion") == 2) { "過去AI仮想成績の形式が不正です" }
        require(root.optString("strategyId") == STRATEGY_ID) { "過去AI仮想成績のstrategyが不正です" }
        require(root.optInt("windowDays") == WINDOW_DAYS) { "過去AI仮想成績の期間が不正です" }
        val forecast = root.optJSONObject("forecast") ?: error("forecast がありません")
        require(!forecast.optBoolean("marketInputs", true)) { "市場入力を含む予想は表示しません" }
        val allocation = root.optJSONObject("allocation") ?: error("allocation がありません")
        require(allocation.optInt("pointsMin") == 4 && allocation.optInt("pointsMax") == 8) { "買い目点数が不正です" }
        require(allocation.optInt("budgetMin") == 1000 && allocation.optInt("budgetMax") == 3000) { "投資額範囲が不正です" }
        require(allocation.optInt("stakeStep") == 100) { "投資単位が不正です" }
        require(allocation.optBoolean("postRaceOddsInputs", false)) { "終了後オッズ検証フラグがありません" }
        require(!allocation.optBoolean("resultUsedForSelection", true)) { "結果利用データは表示しません" }
        val settlement = root.optJSONObject("settlement") ?: error("settlement がありません")
        require(!settlement.optBoolean("preCloseOddsClaim", true)) { "締切前ROIを名乗るデータは受け付けません" }

        val recordsJson = root.optJSONArray("records") ?: error("records がありません")
        val records = buildList {
            for (index in 0 until recordsJson.length()) {
                val record = PredictionRecord.fromJson(recordsJson.getJSONObject(index))
                if (record.strategyId != STRATEGY_ID || !record.settled || !record.evaluationEligible) continue
                if (record.combinations.size !in 4..8 || record.simulatedStake !in 1000..3000 || record.simulatedStake % 100 != 0) continue
                add(record)
            }
        }.distinctBy { it.id }.sortedWith(compareBy<PredictionRecord> { it.date }.thenBy { it.stadiumNumber }.thenBy { it.raceNumber })
        val summaryJson = root.optJSONObject("summary")
        val breakdownJson = summaryJson?.optJSONObject("pointBreakdown")
        val breakdown = (4..8).mapNotNull { points -> breakdownJson?.optJSONObject(points.toString())?.let { b ->
            ModelARecentPointBreakdown(points, b.optInt("races"), b.optInt("hits"), b.optDouble("hitRate"), b.optInt("stake"), b.optInt("payout"), b.optInt("profit"), b.optDouble("roi"), b.optDouble("averageStake"), b.optDouble("averageWinningPayout"))
        }}
        val summary = summaryJson?.let { s -> ModelARecentVirtualSummary(s.optInt("races"), s.optInt("hits"), s.optInt("stake"), s.optInt("payout"), s.optInt("profit"), s.optDouble("roi"), s.optDouble("averagePoints"), s.optDouble("averageStake"), breakdown) }
        return ModelARecentVirtualLoadResult(records, root.optString("throughDate").takeIf { it.isNotBlank() }, root.optString("windowStart").takeIf { it.isNotBlank() }, root.optString("generatedAt").takeIf { it.isNotBlank() }, summary = summary)
    }

    private fun httpGet(url: String): String {
        val connection = (URL(url).openConnection() as HttpURLConnection).apply {
            requestMethod = "GET"
            connectTimeout = 12_000
            readTimeout = 25_000
            useCaches = false
            setRequestProperty("User-Agent", "BOAT-AI-Android/${BuildConfig.VERSION_NAME}")
            setRequestProperty("Accept", "application/json")
            setRequestProperty("Cache-Control", "no-cache")
        }
        return try {
            val status = connection.responseCode
            if (status !in 200..299) throw IllegalStateException("HTTP $status")
            connection.inputStream.bufferedReader().use { it.readText() }
        } finally {
            connection.disconnect()
        }
    }

    companion object {
        const val STRATEGY_ID = "model-a-retro-flex-v2"
        const val WINDOW_DAYS = 30
        private const val KEY_CACHE = "latest_json"
        private const val REMOTE_URL =
            "https://raw.githubusercontent.com/daisuke05221995-cpu/BOAT-AI/main/data/model_a_recent_virtual_results.json"
    }
}
