#!/usr/bin/env python3
"""Build Android parity fixtures from already-opened Jul-Aug 2025 pre-race features.

Only pre-race arrays are accessed from the frozen r4 development feature artifact.
No outcomes, payouts, odds, September data or Q4 data are read. The expected 120-way
probabilities are generated by the frozen Python Model A implementation.
"""
import argparse
import json
from pathlib import Path

import lightgbm as lgb
import numpy as np

from v016_r2_model import predict


def text(value):
    value = float(value)
    if np.isnan(value):
        return "NaN"
    if np.isposinf(value) or np.isneginf(value):
        raise ValueError("Infinite fixture value")
    return format(value, ".17g")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--feature-cache", type=Path, required=True)
    parser.add_argument("--model-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--races", type=int, default=64)
    args = parser.parse_args()

    if lgb.__version__ != "4.6.0":
        raise RuntimeError(f"Pinned LightGBM 4.6.0 required, got {lgb.__version__}")
    if args.races < 32:
        raise ValueError("At least 32 races are required")

    manifest = json.loads((args.model_dir / "manifest.json").read_text())
    if manifest.get("variant") != "reaction" or manifest.get("temperature") != 1.0:
        raise ValueError("Unexpected frozen Model A manifest")
    if manifest.get("marketInOutcomeModel") is not False:
        raise ValueError("Market input unexpectedly enabled")

    # Deliberately name and access only pre-race arrays. actual_index, amount, odds
    # and odds_usable exist in the research cache but are never read here.
    with np.load(args.feature_cache, allow_pickle=False) as z:
        current = z["current"]
        history = z["history"]
        reaction = z["reaction"]
        global_features = z["global_features"]
        venue = z["venue"]
        race_number = z["race_number"]
        month = z["month"]
        usable = z["usable"]

    if set(np.unique(month).tolist()) != {7, 8}:
        raise ValueError("Parity cache must be already-opened July-August development only")
    if current.shape[1:] != (6, 30) or history.shape[1:] != (6, 32) or reaction.shape[1:] != (6, 20):
        raise ValueError(f"Frozen feature schema drift: {current.shape}, {history.shape}, {reaction.shape}")
    if global_features.shape[1] != 22:
        raise ValueError(f"Frozen global schema drift: {global_features.shape}")

    eligible = np.flatnonzero(usable)
    if len(eligible) < args.races:
        raise ValueError("Insufficient usable pre-race races")
    positions = np.linspace(0, len(eligible) - 1, args.races, dtype=int)
    take = eligible[positions]
    if len(np.unique(take)) != args.races:
        raise ValueError("Sample index collision")

    boat = np.concatenate([current[take], history[take], reaction[take]], axis=2).astype(np.float32)
    source_global = global_features[take].astype(np.float32)
    r = reaction[take]
    weak = np.maximum(r[:, 0, 1], 0) + np.maximum(r[:, 0, 3], 0)
    strong = ((r[:, 1:, 1] <= -0.5) | (r[:, 1:, 3] <= -0.5)).sum(axis=1)
    reaction_global = np.concatenate(
        [source_global[:, :-2], weak[:, None], strong[:, None], source_global[:, -2:]], axis=1
    ).astype(np.float32)
    if reaction_global.shape != (args.races, 24):
        raise ValueError("Reaction global feature shape drift")

    models = {}
    for stage in range(3):
        path = args.model_dir / f"stage{stage}.txt"
        booster = lgb.Booster(model_file=str(path))
        if booster.num_feature() != manifest["stages"][str(stage)]["features"]:
            raise ValueError("Frozen model feature count drift")
        models[stage] = booster

    c = {
        "year": np.asarray([2025]),
        "combos": np.asarray([], dtype="U1"),
        "month": month[take],
        "boat": boat,
        "global_features": reaction_global,
        "venue": venue[take],
        "race_number": race_number[take],
        # Uniform placeholder exactly as v016_r4_model.inputs(..., 'reaction').
        "market_p": np.full((args.races, 120), 1 / 120, np.float32),
    }
    probabilities = predict(c, "fundamental", models)
    if probabilities.shape != (args.races, 120):
        raise ValueError("Unexpected prediction shape")
    if not np.isfinite(probabilities).all() or not np.allclose(probabilities.sum(axis=1), 1, atol=1e-7):
        raise ValueError("Invalid frozen Python probabilities")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        for i in range(args.races):
            boat_text = ",".join(text(v) for v in boat[i].reshape(-1))
            global_text = ",".join(text(v) for v in reaction_global[i])
            probability_text = ",".join(text(v) for v in probabilities[i])
            f.write(
                boat_text
                + "|"
                + global_text
                + "|"
                + str(int(venue[take[i]]))
                + "|"
                + str(int(race_number[take[i]]))
                + "|"
                + probability_text
                + "\n"
            )

    summary = {
        "lightgbmVersion": lgb.__version__,
        "sourcePeriod": "2025-07-01..2025-08-31",
        "races": args.races,
        "boatFeaturesPerLane": 82,
        "globalFeatures": 24,
        "probabilitiesPerRace": 120,
        "outcomesRead": False,
        "oddsRead": False,
        "septemberRead": False,
        "q4Read": False,
    }
    args.output.with_suffix(".json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary))


if __name__ == "__main__":
    main()
